version: '3.8'

services:
  evoi-clock-test:
    build: .
    volumes:
      - .:/app
    environment:
      - DISPLAY=host.docker.internal:0.0
    ports:
      - "8080:8080"
    command: python main.py 