"""
This is a setup.py script generated by py2app for building the EVOI Clock.

This script packages the Python application into a standalone macOS app bundle.
It includes specific options to make the application behave like a desktop widget,
such as hiding the Dock icon.

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP_NAME = 'EVOI Clock'
APP_SCRIPT = 'evoi_final.py'

# --- Options for py2app ---
OPTIONS = {
    # List of packages to include. py2app might not find them automatically.
    'packages': ['cnlunar'],
    # Force include packages that are sometimes missed.
    'includes': ['cnlunar'],
    
    # The plist dictionary is used to configure the app's metadata.
    'plist': {
        'CFBundleName': APP_NAME,
        'CFBundleDisplayName': APP_NAME,
        'CFBundleGetInfoString': "EVOI Multi-state Trading Clock",
        'CFBundleIdentifier': "com.evoi.clockwidget",
        'CFBundleVersion': "4.1.0",
        'CFBundleShortVersionString': "4.1",
        # LSUIElement=True makes it a background app (no dock icon), perfect for a widget.
        'LSUIElement': True,
    },
    
    # You can uncomment the line below and provide a path to a .icns file
    # to give your app a custom icon.
    # 'iconfile': 'assets/app_icon.icns',
}

# --- Setup configuration ---
setup(
    app=[APP_SCRIPT],
    name=APP_NAME,
    data_files=[],
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
) 