name: Build EvoiClock for Windows

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Convert PNG to ICO using Pillow
        run: python -c "from PIL import Image; img = Image.open('icon-shark2.png'); img.save('EvoiClock.ico', format='ICO', sizes=[(256,256)])"

      - name: '[DEBUG] List files before building'
        run: |
          echo "--- Listing all files recursively ---"
          dir /s
        shell: cmd

      - name: Run PyInstaller
        run: pyinstaller --noconfirm --onefile --windowed --name EvoiClock --icon "EvoiClock.ico" --add-data "assets;assets" --add-data "icon-shark2.png;." --distpath "dist" "evoi_final.py"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: EvoiClock-windows-exe
          path: dist/EvoiClock.exe 